<a href="https://colab.research.google.com/github/engineerchacon/Maestria-en-Inteligencia-Artificial-y-Analitica-de-Datos-Colab-Files/blob/main/Pr%C3%A1ctica_4_Unidad_1_Manipulaci%C3%B3n_de_matrices_Armando_Chacon_Terrazas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Instrucciones:**

Manipulación de matrices.

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1-Suma ambas matrices.
2-Resta la segunda matriz de la primera.
3-Multiplica la primera matriz por 2.
4-Realiza una multiplicación matricial entre las dos matrices.

# **Conexión  a Google Drive**

In [1]:
#Conexión a Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## **Importamos la biblioteca NumPy**

In [2]:
import numpy as np

# **Crear matriz 1**

In [5]:
# Crear matriz 3x3 con valores aleatorios entre 1 y 10 usando np.random.randint
matriz1 = np.random.randint(1, 11, (3, 3))
print("Matriz 1:")
print(matriz1)

Matriz 1:
[[ 3  4  8]
 [ 1  2  9]
 [ 7 10  2]]


# **Crear matriz 2**

In [6]:
# Crear matriz 3x3 con valores aleatorios entre 1 y 10 usando np.random.randint
matriz2 = np.random.randint(1, 11, (3, 3))
print("Matriz 2:")
print(matriz2)

Matriz 2:
[[ 9  3  6]
 [ 6  1  4]
 [ 1 10 10]]


# **Suma ambas matrices**

In [7]:
sumar = matriz1 + matriz2
print("\nSuma de matrices:")
print(sumar)


Suma de matrices:
[[12  7 14]
 [ 7  3 13]
 [ 8 20 12]]


# **Resta la segunda matriz de la primera.**

In [13]:
restar = matriz1 - matriz2
print("\nResta (Matriz 1 - Matriz 2):")
print(restar)


Resta (Matriz 1 - Matriz 2):
[[-6  1  2]
 [-5  1  5]
 [ 6  0 -8]]


# **Multiplica la primera matriz por 2**

In [12]:
multiplicacion = matriz1 * 2
print("\nMatriz 1 multiplicada por 2:")
print(multiplicacion)


Matriz 1 multiplicada por 2:
[[ 6  8 16]
 [ 2  4 18]
 [14 20  4]]


# **Multiplicación matricial entre las dos matrices**

In [14]:
mult_matricial = np.dot(matriz1, matriz2)
print("\nMultiplicación matricial (Matriz 1 x Matriz 2):")
print(mult_matricial)


Multiplicación matricial (Matriz 1 x Matriz 2):
[[ 59  93 114]
 [ 30  95 104]
 [125  51 102]]
